export enum OrdersMutationTypes {
  FETCH_ORDERS = 'FETCH_ORDERS',
  REMOVE_ORDER = 'REMOVE_ORDER',
  APPROVE_ORDER = 'APPROVE_ORDER',
  CREATE_ORDER = 'CREATE_ORDER',
  ORDERS_LOADING = 'ORDERS_LOADING',
  ORDERS_SUCCEEDED = 'ORDERS_SUCCEEDED',
  ORDERS_ERROR = 'ORDERS_ERROR',
}
